### ISSUE TITLE
Exception during loot table addition/injection

### ISSUE THREAD

**Issue by darkphan** [AzureDoom/Azure-RPG-Items#1]
Seems this mod causes some loot table to break while injecting loot to the table.

Here is a snippet from the log file: https://pste.me/#/uArG2

**Comment by AzureDoom** [comment]
What version is this for? I support 1.12.2/1.14.4/1.15.1

**Comment by darkphan** [comment]
Oops, meant to put that info in here, but got a bit side tracked. It was for 1.14.4, and it seems you fixed this issue already.

**Comment by AzureDoom** [comment]
Yup was an issue in both this mod and Behgamon. Fixed in both.
